import { Inter } from "next/font/google";
import { AuthProvider } from "@/components";
import "./globals.css";
import "remixicon/fonts/remixicon.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={`${inter.className}`}>
        <div className="bg-base-100 scroll-m-0">
          <AuthProvider>{children}</AuthProvider>
        </div>
      </body>
    </html>
  );
}
